version: "3"
services:
    nginx:
        build: ./nginx
        image: nginx:8888
        container_name: nginx
        ports:
            - "8888:8888"
        volumes:
            # - ./nginx:/etc/nginx/conf.d
            # - /home/ubuntu/static:/static
            - test_volume:/static
        depends_on:
            - web

    web:
        build: .
        image: django:gunicorn4
        container_name: django
        command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn --bind 0.0.0.0:8000 config.wsgi:application"
        volumes:
        #     - /home/ubuntu/static:/home/ubuntu/static
              - test_volume:/home/ubuntu/static
        # ports:
        #    - "8000:8000"
        expose:
            - "8000"
        command:
                bash -c "python manage.py collectstatic && gunicorn --bind 0.0.0.0:8000 config.wsgi:application"

volumes:
  test_volume:
